from apps.home_app import HomeApp
from apps.introduction_app import IntroductionApp
from apps.about_me import AboutMe
from apps.eda_automation.main import EdaApp
from apps.flood_analysis.main import FloodApp
from apps.sentiment_analysis.main import SentimentApp
from apps.business_expansion.main import BEApp
from apps.similarity.main import SimilarityApp
from apps.project.main import ProjectApp
from apps.modelBuilding.main import ModelBuildingApp